README.md, demo/index.html, package.json, src/components/Body/styles/_mixins.scss, src/components/Button/styles/_mixins.scss, src/components/Button/styles/_styles.scss, src/components/Header/styles/_mixins.scss, src/components/Input/styles/_mixins.scss, src/components/Input/styles/_styles.scss, src/components/List/styles/_mixins.scss, src/components/Navigation/styles/_mixins.scss, src/components/Navigation/styles/_styles.scss, src/components/Panel/styles/_mixins.scss, src/components/Panel/styles/_styles.scss, src/components/Sample/styles/_mixins.scss, src/components/Sample/styles/_styles.scss, src/components/Textarea/styles/_mixins.scss, src/components/Textarea/styles/_styles.scss, src/mixes/_pull-right.scss, src/style.scss, src/variables/_brand.scss, src/variables/_colors.scss, src/variables/_typography.scss
**Business justification:** https://trello.com/c/lhiMkyFS/2-graphn-2-general-code-cleanup
**Description:** Remove dependency from Twitter Bootstrap and restructurize the framework to be more flexible.
=> GRAPHN-2 - General code cleanup

docs/_site/changelogs/CHANGELOG_v0.0.3.md, docs/_site/stylesheets/styles.css, docs/stylesheets/styles.css, src/components/Switch/styles/_mixins.scss, src/mixins/_responsiveness.scss, src/style.scss
**Business justification:** https://trello.com/c/wq5ra6S4/6-graphn-implement-responsiveness
**Description:** Implement responsiveness mixins.
=> GRAPHN-6 - Implement responsiveness

docs/_site/changelogs/CHANGELOG_v0.0.5.md, docs/_site/index.html, docs/_site/stylesheets/styles.css, docs/index.html, docs/stylesheets/styles.css, src/components/Led/styles/_mixins.scss, src/components/Led/styles/_styles.scss, src/style.scss
**Business justification:** https://trello.com/c/pP6sXJuI/7-graphn-implement-led-components
**Description:** Implement LED component.
**Visual overview:**
=> GRAPHN-7 - Implement LED components

README.md, src/components/Switch/styles/_mixins.scss
**Business justification:** https://trello.com/c/9Rin1wrk/2-grhn-9-safari-mobile-toggle-has-rounded-border
**Description:** Fix switch bordering which was 'default like' in Safari (both mobile and desktop).
=> GRHN-9 - Safari mobile: toggle has rounded border

README.md
**Business justification:** Add build status is required
**Description:** This PR adds travis build status.
=> GRAPHN-11 - Integrate build status

.npmrc, .travis.yml, Makefile
**Business justification:** https://trello.com/c/PHN19CJS/39-coda-39-add-npm-deployment
**Description:** Add automatic npm deployment (publish).
=> CODA-39 - Add npm deployment

.travis.yml, package.json
**Business justification:** https://trello.com/c/ZVS9KJaF/40-coda-40-fix-npm-deployment
**Description:** Fix npm deployment.
=> CODA-40 - Fix npm deployment

package-lock.json, package.json, src/components/Accordion/styles/_styles.scss, src/style.scss
**Business justification:** https://trello.com/c/rr8iD20w/42-coda-42-change-nam-entry-point
**Description:** Adjust Accordion animation, also introduce some minor npm fixed.
=> CODA-42 - Adjust accordion component

package-lock.json, package.json, src/components/Accordion/index.jsx, src/components/Link/index.jsx, src/example.jsx
**Business justification:** https://trello.com/c/JozRWDBq/43-coda-43-add-iscollapsed-as-a-property
**Description:** Add to `Accordion` component `isCollapsed` property as an initial state. Also leverage dependencies.
=> CODA-43 - Add `isCollapsed` as a property

src/components/Accordion/index.jsx
**Business justification:** https://trello.com/c/Gt9aGipE/44-coda-44-allow-to-add-custom-classes-to-accordion-component
**Description:** Allow to add custom classes to accordion component.
=> CODA-44 - Allow to add custom classes to accordion component

src/typography/_icons.scss
**Business justification:** https://trello.com/c/iRl6Tcwr/47-coda-47-fix-icon-font-bug
**Description:** Add icon url config variable accessible from root project. Also fix minor icon bug.
=> CODA-47 - Add config variable for icon url

scripts/changelog.sh
**Business justification:** https://trello.com/c/jbNQqpj0/49-coda-49-upgrade-sh-versioner
**Description:** Upgrade sh-versioner.
=> CODA-49 - Upgrade sh-versioner

README.md, src/mixes/_pull-right.scss, src/mixins/_responsiveness.scss, src/variables/_responsiveness.scss
**Business justification:** https://trello.com/c/y2LdSOCz/51-coda-51-fix-responsiveness
**Description:** Fix responsiveness breakpoint for `phone`, also start prefixing everything slowly. Update README.md.
=> CODA-51 - Fix responsiveness

src/components/Button/styles/_mixins.scss, src/components/Button/styles/_styles.scss, src/components/Input/styles/_styles.scss, src/components/Switch/styles/_mixins.scss, src/components/Textarea/styles/_styles.scss, src/example.jsx, src/variables/_sizes.scss
**Business justification:** https://trello.com/c/a17mhlFv/27-coda-27-multiple-minor-ui-updates
**Description:** Introduce the following changes:
* introduce roundings (ex. to buttons / forms / switches)
* add separators to the example app
* fix button height padding in regards to font
=> CODA-27 - Multiple minor UI updates

.travis.yml, src/components/Accordion/index.jsx, src/components/Alert/styles/_styles.scss, src/components/Input/styles/_styles.scss, src/components/Led/styles/_mixins.scss, src/components/Led/styles/_styles.scss, src/components/Sample/styles/_styles.scss, src/components/Textarea/styles/_styles.scss, src/example.jsx, src/variables/_brand.scss, src/variables/_colors.scss
**Business justification:** https://trello.com/c/KVN1keqq/34-coda-34-restyle-forms-and-accordion
**Description:** 
* Restyle forms - labels in particular
* Make accordion icon smaller
* Restyle leds
* Add info alert
=> CODA-34 -  Restyle forms and accordion

src/components/Button/styles/_styles.scss
**Business justification:** https://trello.com/c/t3Q2TKXD/31-coda-31-fix-button-vertical-alignment
**Description:** Revert vertical alignment for buttons removed in the last change.
=> CODA-31 - Fix button vertical alignment

src/components/Body/Footer/styles/_styles.scss, src/components/Body/Header/styles/_styles.scss, src/components/Body/styles/_styles.scss, src/components/Button/styles/_styles.scss, src/components/Card/styles/_styles.scss, src/components/Input/styles/_styles.scss, src/components/Link/styles/_styles.scss, src/components/List/styles/_styles.scss, src/components/Navigation/styles/_styles.scss, src/components/Sample/styles/_styles.scss, src/components/Scroller/styles/_styles.scss, src/components/Switch/styles/_mixins.scss, src/components/Textarea/styles/_styles.scss, src/example.jsx, src/variables/_brand.scss
**Business justification:** https://trello.com/c/iYtpJ33F/22-coda-22-cleanup-branding-names
**Description:** Make branding variables naming more consistent.
=> CODA-22 - Cleanup branding names

README.md, src/components/Panel/styles/_styles.scss, src/variables/_brand.scss
**Business justification:** https://trello.com/c/BlJw1XXY/53-coda-53-add-variable-customisation
**Description:** Allow to overwrite branding variables.
=> CODA-53 - Add branding customization

src/components/Button/styles/_mixins.scss
**Business justification:** https://trello.com/c/Ow5Oz43G/20-coda-20-fix-button-height-calculation
**Description:** Remove `height` form button height calculation and rely only on `line-height`.
=> CODA-20 - Fix button height calculation

src/components/Panel/styles/_styles.scss, src/example.jsx
**Business justification:** https://trello.com/c/XW4DMyKo/21-coda-21
**Description:** Improve styling and example usecase for 'Card' component.
=> CODA-21 - Improve 'Card' component styling

src/components/Card/styles/_styles.scss, src/components/Panel/styles/_styles.scss, src/example.jsx
**Business justification:** https://trello.com/c/yx32Mv36/58-coda-fix-panel-layouting
**Description:** Panels shouldn't override background color, not should be stretched to 100% of height as it's parents not always had fixed heights.
=> CODA-58 - Fix panel layouting

src/components/Button/index.jsx, src/components/Dialog/index.jsx, src/components/Dialog/styles/_styles.scss, src/example.jsx, src/index.js, src/style.scss
**Business justification:** https://trello.com/c/k18YpBJI/59-coda-59-add-dialog-component
**Description:** Add dialog component.
=> CODA-59 - Add dialog component

src/components/Input/index.jsx, src/components/Input/styles/_styles.scss, src/components/Tooltip/index.jsx, src/components/Tooltip/styles/_styles.scss, src/components/Validation/index.jsx, src/components/Validation/styles/_styles.scss, src/example.jsx, src/index.js, src/style.scss
**Business justification:** https://trello.com/c/2iLoAw6h/60-coda-60-validation-component
**Description:** Add validation component for input fields.
=> CODA-60 - Validation component

src/components/Input/index.jsx, src/components/Validation/styles/_styles.scss
**Business justification:** https://trello.com/c/hO46kIEa/61-coda-cleanup-input-with-validation
**Description:** Fix minor bugs related with input field validation.
=> CODA-61 - Cleanup input with validation

src/components/Button/styles/_mixins.scss, src/components/Button/styles/_styles.scss, src/example.jsx, src/variables/_brand.scss, src/variables/integration/colors.spec.js
**Business justification:** https://trello.com/c/a2lukIYA/63-coda-replace-semantics-with-hierarchy-in-buttons
**Description:** Semantic buttons didn't play well into projects and were hard to fit-in. Instead hierarchical buttons are introduced.
=> CODA-63 - Replace semantics with hierarchy in buttons

src/components/Dialog/styles/_styles.scss
**Business justification:** https://trello.com/c/fxJI3Tlp/65-coda-65-remove-unnecessary-dialog-size-constraints
**Description:** Remove unnecessary dialog size constraints.
=> CODA-65 - Remove unnecessary dialog size constraints

src/components/Navigation/styles/_submenu.scss
**Business justification:** https://trello.com/c/UtwpK9F6/93-coda-fix-dropdown-z-index
**Description:** Fix z-index for navigation dropdown.
=> CODA-93 - Fix dropdown z-index

README.md
**Business justification:** https://trello.com/c/NjkEqfep/94-coda-94-update-readmemd-with-development-steps
**Description:** Add development steps to `README.md`.
=> CODA-94 - Update README.md with development steps

src/components/Flex/styles/_styles.scss, src/mixes/_alignments.scss, src/mixes/_spacing.scss, src/style.scss
**Business justification:** https://trello.com/c/lKS9RgJv/96-coda-96-update-generic-layouting-styles
**Description:** Add generic layouting styles.
=> CODA-96 - Update generic layouting styles

src/components/Body/styles/_styles.scss
**Business justification:** https://trello.com/c/n3DgjWC5/101-coda-101-fix-page-min-height
**Description:** Fix body min-height when content doesn't fill page to full height.
=> CODA-101 - Fix page min-height

.eslintrc, .flowconfig, src/components/Accordion/index.jsx, src/components/Link/index.jsx, src/components/Link/styles/_styles.scss, src/example.jsx, src/index.js, src/variables/constants.js, webpack.dev.config.js, webpack.example.config.js, webpack.prod.config.js
**Business justification:** https://trello.com/c/yIquZPuo/105-coda-105-extend-link-styling
**Description:**
=> CODA-105 - Extend Link styling

src/components/Dropdown/index.jsx, src/variables/integration/dropdown.spec.js
**Business justification:** https://trello.com/c/bkwHXcwP/120-coda-120-dropdown-integration-tests
**Description:** Add dropdown integration test
=> CODA-120 - Dropdown integration tests

src/components/Dropdown/styles/_styles.scss
**Business justification:** https://trello.com/c/EnU18Q72/123-coda-123-unnecessary-dropdown-shadow
**Description:** Delete unnecessary shadow in dropdown button
=> CODA-123 - Unnecessary dropdown shadow

package-lock.json, package.json
**Business justification:** https://trello.com/c/5Klj8hYj/139-coda-139-peerdependencies-issue
**Description:** Fix `peerDependencies` issue.
=> CODA-139 - peerDependencies issue

src/index.js
**Business justification:** https://trello.com/c/RAuMUTCP/141-coda-141-fix-hook-call-error
**Description:** Change paths to absolute, they are more convenient for webpack.
=> CODA-141 - Fix hook call error

src/components/Dropdown/index.jsx
**Business justification**: https://trello.com/c/7HMAGfgT/142-coda-142-dropdown-fixes
**Description**: add "items" to dependencies in selectItem function
=> CODA-142 - Dropdown fixes

webpack.example.config.js
**Business justification:** https://trello.com/c/IwWrPtt0/263-coda-update-minifier
**Description:** Update minifier after webpack migration.
=> CODA-263 - Update minifier

package-lock.json, package.json
**Business justification:** https://trello.com/c/5mJ23Zu9/271-coda-update-reactjs-version-to-v1820
**Description:** Update `React.js` version to `v18.2.0`.
=> CODA-271 - Update React.js version to v18.2.0

.github/workflows/build.yml, .github/workflows/test.yml
**Business justification:** https://trello.com/c/CnTpveNa/301-coda-301-fix-npm-publishing
**Description:** Fix npm package publishing.
=> CODA-301 - Fix npm publishing

src/components/Dropdown/index.tsx, src/components/Dropdown/integration/dropdown.spec.js, src/example.tsx
**Business justification:** https://trello.com/c/meXrrA1r/307-coda-307-remove-margin-for-dropdown-without-label
**Description:** Remove margin for dropdown without label.
=> CODA-307 - Remove margin for dropdown without label

src/components/Body/Header/styles/_styles.scss, src/components/Dropdown/styles/_mixins.scss, src/components/Dropdown/styles/_styles.scss, src/components/Navigation/styles/_styles.scss, src/example.tsx
**Business justification:** https://trello.com/c/oJ7kSZ8F/304-coda-304-mobile-admin-navigation
**Description:** UI improvements related with mobile navigation enchancement.
=> CODA-304 - Mobile admin navigation

src/components/Dropdown/index.tsx, src/components/Dropdown/styles/_styles.scss
**Business justification:** https://trello.com/c/uVCPkTW6/326-coda-326-dropdown-improvements
**Description:** Dropdown UI/UX improvements along with dynamic change of initial state.
=> CODA-326 - Dropdown improvements
